services:
  spark:
    build: .
    volumes:
      - .:/app
      - ./data:/data
    command: ["spark-submit", "--packages", "io.delta:delta-core_2.12:2.4.0", "src/main.py"]
    ports:
      - "4040:4040"
    env_file:
      - .env

  tests:
    build: .
    volumes:
      - .:/app
      - ./data:/data
      - ./tests:/app/tests
      - ./coverage_html:/app/coverage_html
    command: ["pytest", "--cov=src", "--cov-report=html:coverage_html", "tests/"]
    environment:
      - PYTHONUNBUFFERED=1
    
  coverage:
    image: python:3.10
    working_dir: /app/coverage_html
    volumes:
      - ./coverage_html:/app/coverage_html
    command: ["python", "-m", "http.server", "8081"]
    ports:
      - "8081:8081"
    depends_on:
      - tests